### ISSUE TITLE
Give bug

### ISSUE THREAD

**Issue by NTKonzen** [n-lambert/Inn-At-The-Edge-of-Copyright#220]
As a user when I enter give <anything> I get no response on the client side, but a large error prints out on the server side that says 
```
 ERROR IN increment player DB CALL
[server] (node:15319) UnhandledPromiseRejectionWarning: MongoError: The path 'inventory' must exist in the document in order to apply array updates.
[server]     at Function.create (/Users/nicholaskonzen/web/projects/Inn-At-The-Edge-of-Copyright/node_modules/mongodb/lib/core/error.js:57:12)
[server]     at toError (/Users/nicholaskonzen/web/projects/Inn-At-The-Edge-of-Copyright/node_modules/mongodb/lib/utils.js:123:22)
[server]     at /Users/nicholaskonzen/web/projects/Inn-At-The-Edge-of-Copyright/node_modules/mongodb/lib/operations/common_functions.js:379:39
[server]     at handler (/Users/nicholaskonzen/web/projects/Inn-At-The-Edge-of-Copyright/node_modules/mongodb/lib/core/sdam/topology.js:942:24)
[server]     at /Users/nicholaskonzen/web/projects/Inn-At-The-Edge-of-Copyright/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
[server]     at handleOperationResult (/Users/nicholaskonzen/web/projects/Inn-At-The-Edge-of-Copyright/node_modules/mongodb/lib/core/sdam/server.js:558:5)
[server]     at MessageStream.messageHandler (/Users/nicholaskonzen/web/projects/Inn-At-The-Edge-of-Copyright/node_modules/mongodb/lib/cmap/connection.js:277:5)
[server]     at MessageStream.emit (events.js:315:20)
[server]     at processIncomingData (/Users/nicholaskonzen/web/projects/Inn-At-The-Edge-of-Copyright/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
[server]     at MessageStream._write (/Users/nicholaskonzen/web/projects/Inn-At-The-Edge-of-Copyright/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
[server]     at doWrite (_stream_writable.js:403:12)
[server]     at writeOrBuffer (_stream_writable.js:387:5)
[server]     at MessageStream.Writable.write (_stream_writable.js:318:11)
[server]     at Socket.ondata (_stream_readable.js:716:22)
[server]     at Socket.emit (events.js:315:20)
[server]     at addChunk (_stream_readable.js:295:12)
[server] (node:15319) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

**Comment by rebgrasshopper** [comment]
User is now given a failure message with instructions on how to use give syntax when entering give with no further text, and the give function is then exited with a value of false to avoid running doomed DB calls.
